import { getEnv } from "@/lib/utils";

export const API_AUTH_URL = getEnv("NEXT_PUBLIC_API_AUTH_URL");
export const API_ROOT_URL = getEnv("NEXT_PUBLIC_API_ROOT_URL");
export const BASE_SOCKET_URL = getEnv("NEXT_PUBLIC_BASE_SOCKET_URL");
export const TEST_CHAT_SOCKET_URL = getEnv("NEXT_PUBLIC_TEST_CHAT_SOCKET_URL");
export const FACEBOOK_CLIENT_ID = getEnv("NEXT_PUBLIC_FACEBOOK_CLIENT_ID");
export const FACEBOOK_CONFIG_ID = getEnv("NEXT_PUBLIC_FACEBOOK_CONFIG_ID");
export const FACEBOOK_AUTHORIZE_URL = getEnv("NEXT_PUBLIC_FACEBOOK_AUTHORIZE_URL");
export const FACEBOOK_INTEGRATION_REDIRECT_URI = getEnv(
  "NEXT_PUBLIC_FACEBOOK_INTEGRATION_REDIRECT_URI",
);
export const GOOGLE_CLIENT_ID = getEnv("NEXT_PUBLIC_GOOGLE_CLIENT_ID");
export const GOOGLE_REDIRECT_URI = getEnv("NEXT_PUBLIC_GOOGLE_REDIRECT_URI");
export const GOOGLE_AUTHORIZE_URL = getEnv("NEXT_PUBLIC_GOOGLE_AUTHORIZE_URL");
